tg -i=spar_station_01.tg
tg -i=spar_station_02.tg
tg -i=spar_station_03.tg
tg -i=spar_station_04.tg
tg -i=spar_station_05.tg
tg -i=spar_station_06.tg
REM tg -i=spar_station_07.tg
REM tg -i=spar_station_08.tg
REM tg -i=spar_station_09.tg
REM tg -i=spar_station_10.tg
REM tg -i=spar_station_11.tg
REM tg -i=spar_station_12.tg
REM tg -i=spar_station_13.tg
REM tg -i=spar_station_14.tg
REM tg -i=spar_station_15.tg
REM tg -i=spar_station_16.tg
REM tg -i=spar_station_17.tg
REM tg -i=spar_station_18.tg
REM tg -i=spar_station_19.tg
REM tg -i=spar_station_20.tg
REM tg -i=spar_station_21.tg
REM tg -i=spar_station_22.tg
REM tg -i=spar_station_23.tg
REM tg -i=spar_station_24.tg