cp monobeam_2_4p.dat.K renamed_for_spar/monoplane_spar_000_0p.dat.K
cp monobeam_2_6p.dat.K renamed_for_spar/monoplane_spar_000_2p.dat.K
cp monobeam_4_7p.dat.K renamed_for_spar/monoplane_spar_002_5p.dat.K
cp monobeam_6_8p.dat.K renamed_for_spar/monoplane_spar_004_8p.dat.K
cp monobeam_8_9p.dat.K renamed_for_spar/monoplane_spar_007_1p.dat.K
cp monobeam_11_4p.dat.K renamed_for_spar/monoplane_spar_009_8p.dat.K
cp monobeam_14_6p.dat.K renamed_for_spar/monoplane_spar_013_3p.dat.K
cp monobeam_16_3p.dat.K renamed_for_spar/monoplane_spar_015_1p.dat.K
cp monobeam_17_9p.dat.K renamed_for_spar/monoplane_spar_016_9p.dat.K
cp monobeam_19_5p.dat.K renamed_for_spar/monoplane_spar_018_6p.dat.K
cp monobeam_22_2p.dat.K renamed_for_spar/monoplane_spar_021_5p.dat.K
cp monobeam_24_9p.dat.K renamed_for_spar/monoplane_spar_024_5p.dat.K
cp monobeam_27_6p.dat.K renamed_for_spar/monoplane_spar_027_4p.dat.K
cp monobeam_35_8p.dat.K renamed_for_spar/monoplane_spar_036_3p.dat.K
cp monobeam_43_9p.dat.K renamed_for_spar/monoplane_spar_045_2p.dat.K
cp monobeam_52_0p.dat.K renamed_for_spar/monoplane_spar_054_0p.dat.K
cp monobeam_60_2p.dat.K renamed_for_spar/monoplane_spar_062_9p.dat.K
cp monobeam_66_7p.dat.K renamed_for_spar/monoplane_spar_070_0p.dat.K
cp monobeam_68_3p.dat.K renamed_for_spar/monoplane_spar_071_7p.dat.K
cp monobeam_73_2p.dat.K renamed_for_spar/monoplane_spar_077_0p.dat.K
cp monobeam_76_4p.dat.K renamed_for_spar/monoplane_spar_080_5p.dat.K
cp monobeam_84_6p.dat.K renamed_for_spar/monoplane_spar_089_4p.dat.K
cp monobeam_89_4p.dat.K renamed_for_spar/monoplane_spar_094_7p.dat.K
cp monobeam_94_3p.dat.K renamed_for_spar/monoplane_spar_100_0p.dat.K